# SITE CONFIGURATION
baseurl: ""
url: "https://blog.woernfl.xyz"
#url: "http://127.0.0.1"
title: "@woernfl 's blog" # site's title
description: "The place where you will find Florian Woerner's (woernfl) blog posts" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: woernfl # blog's title
  avatar: assets/img/logo.png
  favicon: assets/img/logo.png
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
    <h1>Blog</h1><p><span style="position:relative; right:50px">Where I have been posting stuff</span><br>
    <span style="position:relative; left:50px">around what I have been doing.</span></p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
    See all the source code of this site in <a href="https://github.com/woernfl/blogwoernfl" target="_blank">Github</a>

  # Icons
  rss:  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab: "woernfl"
  github: "woernfl"
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/woernfl/ # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "woernfl" # "twitter username"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr:
    pinterest:
    pocket: true
    reddit:
    linkedin: true
    wordpress:
    email:

  # Scripts / Features 
  google_analytics: "UA-105986496-10" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: false
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
